-- Seed aura_analysis_assets. Run after 001_aura_analysis_tables.sql
-- Uses INSERT IGNORE to skip duplicates on symbol

INSERT IGNORE INTO aura_analysis_assets (symbol, display_name, asset_class, quote_type, pip_multiplier, is_active) VALUES
('EURUSD', 'EUR/USD', 'forex', 'USD', 10000, 1),
('GBPUSD', 'GBP/USD', 'forex', 'USD', 10000, 1),
('USDJPY', 'USD/JPY', 'forex', 'JPY', 100, 1),
('USDCHF', 'USD/CHF', 'forex', 'CHF', 10000, 1),
('USDCAD', 'USD/CAD', 'forex', 'CAD', 10000, 1),
('AUDUSD', 'AUD/USD', 'forex', 'USD', 10000, 1),
('NZDUSD', 'NZD/USD', 'forex', 'USD', 10000, 1),
('EURGBP', 'EUR/GBP', 'forex', 'GBP', 10000, 1),
('EURJPY', 'EUR/JPY', 'forex', 'JPY', 100, 1),
('EURCHF', 'EUR/CHF', 'forex', 'CHF', 10000, 1),
('EURAUD', 'EUR/AUD', 'forex', 'AUD', 10000, 1),
('EURCAD', 'EUR/CAD', 'forex', 'CAD', 10000, 1),
('EURNZD', 'EUR/NZD', 'forex', 'NZD', 10000, 1),
('GBPJPY', 'GBP/JPY', 'forex', 'JPY', 100, 1),
('GBPCHF', 'GBP/CHF', 'forex', 'CHF', 10000, 1),
('GBPAUD', 'GBP/AUD', 'forex', 'AUD', 10000, 1),
('GBPCAD', 'GBP/CAD', 'forex', 'CAD', 10000, 1),
('GBPNZD', 'GBP/NZD', 'forex', 'NZD', 10000, 1),
('AUDJPY', 'AUD/JPY', 'forex', 'JPY', 100, 1),
('AUDCHF', 'AUD/CHF', 'forex', 'CHF', 10000, 1),
('AUDCAD', 'AUD/CAD', 'forex', 'CAD', 10000, 1),
('AUDNZD', 'AUD/NZD', 'forex', 'NZD', 10000, 1),
('NZDJPY', 'NZD/JPY', 'forex', 'JPY', 100, 1),
('NZDCHF', 'NZD/CHF', 'forex', 'CHF', 10000, 1),
('NZDCAD', 'NZD/CAD', 'forex', 'CAD', 10000, 1),
('CADJPY', 'CAD/JPY', 'forex', 'JPY', 100, 1),
('CADCHF', 'CAD/CHF', 'forex', 'CHF', 10000, 1),
('CHFJPY', 'CHF/JPY', 'forex', 'JPY', 100, 1),
('XAUUSD', 'Gold/USD', 'metals', 'USD', 10, 1),
('XAUEUR', 'Gold/EUR', 'metals', 'EUR', 10, 1),
('XAUGBP', 'Gold/GBP', 'metals', 'GBP', 10, 1),
('XAUAUD', 'Gold/AUD', 'metals', 'AUD', 10, 1),
('XAGUSD', 'Silver/USD', 'metals', 'USD', 100, 1),
('XTIUSD', 'WTI Crude', 'energy', 'USD', 100, 1),
('XBRUSD', 'Brent Crude', 'energy', 'USD', 100, 1),
('NATGAS', 'Natural Gas', 'energy', 'USD', 100, 1),
('US30', 'Dow 30', 'indices', 'USD', 1, 1),
('NAS100', 'Nasdaq 100', 'indices', 'USD', 1, 1),
('SPX500', 'S&P 500', 'indices', 'USD', 1, 1),
('GER40', 'DAX', 'indices', 'EUR', 1, 1),
('UK100', 'FTSE 100', 'indices', 'GBP', 1, 1),
('FRA40', 'CAC 40', 'indices', 'EUR', 1, 1),
('EU50', 'Euro Stoxx 50', 'indices', 'EUR', 1, 1),
('JP225', 'Nikkei 225', 'indices', 'JPY', 1, 1),
('HK50', 'Hang Seng', 'indices', 'HKD', 1, 1),
('AUS200', 'ASX 200', 'indices', 'AUD', 1, 1),
('BTCUSD', 'Bitcoin/USD', 'crypto', 'USD', 1, 1),
('ETHUSD', 'Ethereum/USD', 'crypto', 'USD', 1, 1),
('SOLUSD', 'Solana/USD', 'crypto', 'USD', 1, 1);
