-- Seed asset registry. Run after migrations.
insert into public.assets (symbol, display_name, asset_class, quote_type, pip_multiplier, is_active) values
('EURUSD', 'EUR/USD', 'forex', 'USD', 10000, true),
('GBPUSD', 'GBP/USD', 'forex', 'USD', 10000, true),
('USDJPY', 'USD/JPY', 'forex', 'JPY', 100, true),
('USDCHF', 'USD/CHF', 'forex', 'CHF', 10000, true),
('USDCAD', 'USD/CAD', 'forex', 'CAD', 10000, true),
('AUDUSD', 'AUD/USD', 'forex', 'USD', 10000, true),
('NZDUSD', 'NZD/USD', 'forex', 'USD', 10000, true),
('EURGBP', 'EUR/GBP', 'forex', 'GBP', 10000, true),
('EURJPY', 'EUR/JPY', 'forex', 'JPY', 100, true),
('EURCHF', 'EUR/CHF', 'forex', 'CHF', 10000, true),
('EURAUD', 'EUR/AUD', 'forex', 'AUD', 10000, true),
('EURCAD', 'EUR/CAD', 'forex', 'CAD', 10000, true),
('EURNZD', 'EUR/NZD', 'forex', 'NZD', 10000, true),
('GBPJPY', 'GBP/JPY', 'forex', 'JPY', 100, true),
('GBPCHF', 'GBP/CHF', 'forex', 'CHF', 10000, true),
('GBPAUD', 'GBP/AUD', 'forex', 'AUD', 10000, true),
('GBPCAD', 'GBP/CAD', 'forex', 'CAD', 10000, true),
('GBPNZD', 'GBP/NZD', 'forex', 'NZD', 10000, true),
('AUDJPY', 'AUD/JPY', 'forex', 'JPY', 100, true),
('AUDCHF', 'AUD/CHF', 'forex', 'CHF', 10000, true),
('AUDCAD', 'AUD/CAD', 'forex', 'CAD', 10000, true),
('AUDNZD', 'AUD/NZD', 'forex', 'NZD', 10000, true),
('NZDJPY', 'NZD/JPY', 'forex', 'JPY', 100, true),
('NZDCHF', 'NZD/CHF', 'forex', 'CHF', 10000, true),
('NZDCAD', 'NZD/CAD', 'forex', 'CAD', 10000, true),
('CADJPY', 'CAD/JPY', 'forex', 'JPY', 100, true),
('CADCHF', 'CAD/CHF', 'forex', 'CHF', 10000, true),
('CHFJPY', 'CHF/JPY', 'forex', 'JPY', 100, true),
('XAUUSD', 'Gold/USD', 'metals', 'USD', 10, true),
('XAUEUR', 'Gold/EUR', 'metals', 'EUR', 10, true),
('XAUGBP', 'Gold/GBP', 'metals', 'GBP', 10, true),
('XAUAUD', 'Gold/AUD', 'metals', 'AUD', 10, true),
('XAGUSD', 'Silver/USD', 'metals', 'USD', 100, true),
('XTIUSD', 'WTI Crude', 'energy', 'USD', 100, true),
('XBRUSD', 'Brent Crude', 'energy', 'USD', 100, true),
('NATGAS', 'Natural Gas', 'energy', 'USD', 100, true),
('US30', 'Dow 30', 'indices', 'USD', 1, true),
('NAS100', 'Nasdaq 100', 'indices', 'USD', 1, true),
('SPX500', 'S&P 500', 'indices', 'USD', 1, true),
('GER40', 'DAX', 'indices', 'EUR', 1, true),
('UK100', 'FTSE 100', 'indices', 'GBP', 1, true),
('FRA40', 'CAC 40', 'indices', 'EUR', 1, true),
('EU50', 'Euro Stoxx 50', 'indices', 'EUR', 1, true),
('JP225', 'Nikkei 225', 'indices', 'JPY', 1, true),
('HK50', 'Hang Seng', 'indices', 'HKD', 1, true),
('AUS200', 'ASX 200', 'indices', 'AUD', 1, true),
('BTCUSD', 'Bitcoin/USD', 'crypto', 'USD', 1, true),
('ETHUSD', 'Ethereum/USD', 'crypto', 'USD', 1, true),
('SOLUSD', 'Solana/USD', 'crypto', 'USD', 1, true)
on conflict (symbol) do update set
  display_name = excluded.display_name,
  asset_class = excluded.asset_class,
  quote_type = excluded.quote_type,
  pip_multiplier = excluded.pip_multiplier,
  is_active = excluded.is_active;
